### ISSUE TITLE
gatsby-plugin-fontawesome-css plugin issue

### ISSUE THREAD

**Issue by subodhk01** [scorelab/Webiu#48] opened 2021-02-16 12:31 UTC
`gatsby-plugin-fontawesome-css` plugin is used in `gatsby-config.js` but is not `package.json`

**Comment by sachinsom93** [comment] 2021-02-16 12:42
Can I work on this @subodhk01 ?

**Comment by Grumpyyash** [comment] 2021-08-15 06:41
The issue is resolved in one of the PRs! Thanks for your contribution @subodhk01 :)

**Closed by Grumpyyash** 2021-08-15 06:41 UTC
